spring.datasource.url=jdbc:postgresql://localhost:5432/examen_parcial2
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# El puerto 8080 estaba ocupado por otro proceso en mi PC, uso 8081
server.port=8081
